LessonDataモデル、ReportData(通報用)モデルをCodableにした。
MiuraToya/LessonInfoApp pull request #89
Opened 2021-03-13 12:55 UTC by MiuraToya

#74 
・それに伴い、DatabaseManagerクラスでの、FireStoreへの書き込み、取得の処理はデコード、エンコードするようにした。
　classとlesson、callegeNameとcallegeなど同じものを指すものは表記を統一してわかりやすくした。

・ControlFuncからブランチを切ったのでmasterではなくControlFuncにプルリクだしてます。
　こちらのイシューが終わり次第、ControlFuncでの改修は再開します

2021-03-14 17:14 UTC, sakiyamaK requested changes
@MiuraToya コメントしました

2021-03-14 17:14 UTC, sakiyamaK commented on InfoApp.xcodeproj/xcuserdata/toya.xcuserdatad/xcschemes/xcschememanagement.plist
> +			<integer>36</integer>
この変更はなんでしょう？

2021-03-14 17:14 UTC, sakiyamaK commented on InfoApp/API/DatabaseManeger.swift
> +                }
これだとdocumentsが100個あったら100回completionが呼ばれますね

2021-03-14 17:14 UTC, sakiyamaK commented on InfoApp/API/DatabaseManeger.swift
> +            let decoder = Firestore.Decoder()
encoder,decoderはこのDatabaseManagerの至る所で使うでしょうからクラスのパラメータにしておいてもいいですね

2021-03-14 17:14 UTC, sakiyamaK commented on InfoApp/API/DatabaseManeger.swift
> +                completion?(nil)
```
do {
  let hogehoge = try ~~~~
} catch {
}
```
だとcatch書いたりが大変で読みづらいので
```
guard let hogehoge = try? ~~~~ else {
  return
}
```

とtry?にするとシンプルになります

2021-03-14 17:14 UTC, sakiyamaK commented on InfoApp/API/DatabaseManeger.swift
> +            if error != nil {
せっかくライブラリが返してくれたerrorはcompletionで返す設計にしないと、原因の特定ができなくなります

2021-03-14 17:14 UTC, sakiyamaK commented on InfoApp/MVC/Model/ReportData.swift
> +    var reportedUid: String?
本来は投稿されたデータなどにもあらゆるデータにidは持たせるべきで、ここの場合はこんな感じになります
```
struct ReportData: Codable {
  var id: String? //この通報のID
  var reportedUID: String //通報されたユーザのID
  var reporterUID: String //通報したユーザのID
  var lessonID: String //通報対象のデータのID
  var comment: String //通報理由とか
  var createdAt: Date? //このデータが作成された日時
}
```

2021-03-15 07:09 UTC, MiuraToya commented on InfoApp.xcodeproj/xcuserdata/toya.xcuserdatad/xcschemes/xcschememanagement.plist
> +			<integer>36</integer>
調べても出てこなかったので、とりあえずコミットしましたが、こちらは何の変更を意味するのでしょうか？

2021-03-15 07:09 UTC, MiuraToya commented on InfoApp/MVC/Model/ReportData.swift
> +    var reportedUid: String?
たしかに通報理由はあるべきですね。

通報ボタンタップで一旦モーダル遷移して、そこで通報理由を選択させるみたいな機能を実装してみます！
でもそれやるとコミットが多くなりすぎると思うので、これ以外の部分修正してから取り掛かります。

2021-03-15 07:16 UTC, sakiyamaK commented on InfoApp.xcodeproj/xcuserdata/toya.xcuserdatad/xcschemes/xcschememanagement.plist
> +			<integer>36</integer>
さあ...俺も知らないので質問をしてます
コミットしたのは @MiuraToya さんなので責任もって、なぜこの変更をこのPRに入れたのか教えてください

2021-03-18 06:13 UTC, sakiyamaK commented on InfoApp.xcodeproj/xcuserdata/toya.xcuserdatad/xcschemes/xcschememanagement.plist
> +			<integer>36</integer>
質問の回答を入れてください
この変更はなんでしょうか？

2021-03-18 09:57 UTC, sakiyamaK requested changes
@MiuraToya コメントしました

2021-03-18 09:57 UTC, sakiyamaK commented on InfoApp/API/DatabaseManeger.swift
>      func setLessoData(user: UserModel, callege: String, lesson: String, teacher: String, comment: String, level: String, completion: ((Error?) -> Void)? = nil) {
MVC設計なのでなるべくModelをやりとりさせてください

```
func set(lessoData: LessonData) {
}
```

2021-03-18 09:57 UTC, sakiyamaK commented on InfoApp/MVC/Controller/MainViewController/MainViewController.swift
> +                }
returnを不用意に多様すると書き忘れのバグが起きやすいです
まとめられるところはまとめましょう

```
if let error = error {
  if error~~~~ {
    ~~~~~~
  } else if {
    ~~~~~
  } else {
    ~~~~~
  }
  return
}
```

2021-03-18 09:57 UTC, sakiyamaK commented on InfoApp/MVC/Controller/MainViewController/MainViewController.swift
>                      let uid = user.fbId
まとめられるところはまとめましょう
```
guard let _hoge = hoge else { return }
guard let _fuga = fuga else { return }
```

ではなく
```
guard 
let _hoge = hoge, 
let _fuga = fuga else { 
    return 
}
```

2021-03-18 12:10 UTC, MiuraToya reviewed
> @MiuraToya コメントしました



> @MiuraToya コメントしました


> @MiuraToya コメントしました



> @MiuraToya コメントしました

[LessonData]ではなく、LessonDataでやりとりすると、データをひとつずつしか渡せないので、渡した先でtableViewに表示するときにひとつずしかreloadされなかったりするので、ここは配列を渡す形でもいいでしょうか？

2021-03-18 12:11 UTC, MiuraToya commented on InfoApp/API/DatabaseManeger.swift
>      func setLessoData(user: UserModel, callege: String, lesson: String, teacher: String, comment: String, level: String, completion: ((Error?) -> Void)? = nil) {
[LessonData]ではなく、LessonDataでやりとりすると、データをひとつずつしか渡せないので、渡した先でtableViewに表示するときにひとつずしかreloadされなかったりするので、ここは配列を渡す形でもいいでしょうか？

2021-03-18 12:18 UTC, sakiyamaK reviewed
@MiuraToya コメントしました

2021-03-18 12:18 UTC, sakiyamaK commented on InfoApp/API/DatabaseManeger.swift
>      func setLessoData(user: UserModel, callege: String, lesson: String, teacher: String, comment: String, level: String, completion: ((Error?) -> Void)? = nil) {
もちろんそれはいいのですが、もともとこのメソッドの引数がひとつのLessonData分に見えますがいいのでしょうか？問題ないならそうしてください
ここに限らずgithubのコメントで示すものはあくまで参考程度に思って自分でちゃんとした実装には落とし込んでください

2021-03-18 12:18 UTC, sakiyamaK commented on InfoApp.xcodeproj/xcuserdata/toya.xcuserdatad/xcschemes/xcschememanagement.plist
> +			<integer>36</integer>
slackでやりとりした通りです。
分からない変更は「絶対」に入れない

2021-03-18 12:27 UTC, MiuraToya commented on InfoApp/API/DatabaseManeger.swift
>      func setLessoData(user: UserModel, callege: String, lesson: String, teacher: String, comment: String, level: String, completion: ((Error?) -> Void)? = nil) {
わかりました！
問題ないので、ここはこのまま配列を渡す形でいこうと思います。

2021-03-18 14:22 UTC, sakiyamaK requested changes
@MiuraToya コメントしました

2021-03-18 14:22 UTC, sakiyamaK commented on InfoApp/API/DatabaseManeger.swift
>      func setLessoData(user: UserModel, callege: String, lesson: String, teacher: String, comment: String, level: String, completion: ((Error?) -> Void)? = nil) {
伝わってなかったようです。
この指摘しているメソッドの入力をちゃんとレッスンモデルにしましょうという意味です

```
func setLessoData(user: UserModel, callege: String, lesson: String, teacher: String, comment: String, level: String, completion: ((Error?) -> Void)? = nil)
```

2021-03-18 14:22 UTC, sakiyamaK commented on InfoApp/MVC/Controller/MainViewController/MainViewController.swift
> +               return
インデントがめちゃくちゃです

2021-03-18 14:22 UTC, sakiyamaK commented on InfoApp/MVC/Model/ReportData.swift
> +    var reportedUid: String?
ここも伝わってませんね
あらゆるデータにそれ自身のIDを持たせてください

```
struct ReportData: Codable { 
  var id: String? //この通報のID
}
```

2021-03-18 15:51 UTC, MiuraToya commented on InfoApp/MVC/Model/ReportData.swift
> +    var reportedUid: String?
ドキュメントIDはfirestoreで自動生成されます！

2021-03-18 15:51 UTC, MiuraToya commented on InfoApp/API/DatabaseManeger.swift
>      func setLessoData(user: UserModel, callege: String, lesson: String, teacher: String, comment: String, level: String, completion: ((Error?) -> Void)? = nil) {
勘違いしてました。
修正します！

2021-03-19 01:45 UTC, sakiyamaK reviewed
@MiuraToya コメントしました

2021-03-19 01:45 UTC, sakiyamaK commented on InfoApp/MVC/Model/ReportData.swift
> +    var reportedUid: String?
自動生成されるのは知ってます、このデータ構造ではそのIDを把握できません

**あらゆるモデルにIDを持たせてください**

新規作成の場合、IDはないのでnilになるためoptionalです
本来はサーバー側で自動発行されたIDを保存するのですが、firestoreはやってくれないので
フロントのアプリ側で
新規登録 -> firestoreが発行したIDを取得 -> さっき登録したデータにID追加
という流れになります

```
struct ReportData: Codable { var id: String? //この通報のID }
```

2021-03-19 16:14 UTC, sakiyamaK reviewed
@MiuraToya すいません、根本的なところが指導できていませんでした
これって通信エラーが起きた時の考慮もできてますか？
機内モードにしたら通信エラーの動作確認ができますがデータの新規作成時に機内モードだったらどうなりますか？

2021-03-19 16:19 UTC, sakiyamaK approved these changes
@MiuraToya まだ実装で気になることはあるのですがエラー処理が正しく動くようであれば一旦LGTMにしましょうか、お疲れ様でした

![エンジニアを褒めるネコ:LGTM](https://raw.githubusercontent.com/fukayatsu/lttm-crx/master/vendor/%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2%E3%82%92%E8%A4%92%E3%82%81%E3%82%8B%E3%83%8D%E3%82%B3/01_LGTM.png)

2021-03-19 16:45 UTC, MiuraToya commented
> @MiuraToya すいません、根本的なところが指導できていませんでした
> これって通信エラーが起きた時の考慮もできてますか？
> 機内モードにしたら通信エラーの動作確認ができますがデータの新規作成時に機内モードだったらどうなりますか？

2021-03-19 16:57 UTC, MiuraToya commented
> @MiuraToya すいません、根本的なところが指導できていませんでした
> これって通信エラーが起きた時の考慮もできてますか？
> 機内モードにしたら通信エラーの動作確認ができますがデータの新規作成時に機内モードだったらどうなりますか？

考慮してませんでした。
普通なら「投稿しました」というHUDが出ますが、機内モードだと何も表示されないです。
通信状態を戻すと、投稿されました。

2021-03-19 17:00 UTC, sakiyamaK commented
@MiuraToya では異常系の実装も考慮してください。エラーが起きたらユーザに何が起きたのか何をしたらいいのか知らせてください
このPRでやるか別issueにしてやるかは任せます

2021-03-19 17:10 UTC, MiuraToya commented
> @MiuraToya では異常系の実装も考慮してください。エラーが起きたらユーザに何が起きたのか何をしたらいいのか知らせてください
> このPRでやるか別issueにしてやるかは任せます
わかりました！
別issueでやります！

2021-03-19 17:11 UTC, MiuraToya commented
> @MiuraToya では異常系の実装も考慮してください。エラーが起きたらユーザに何が起きたのか何をしたらいいのか知らせてください
> このPRでやるか別issueにしてやるかは任せます

@sakiyamaK 
了解です。別issueでやることにします！

2021-03-19 17:23 UTC, merged